[package]
name = "codec-hackathon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
ffmpeg-next = "7.1.0"
cpal = "0.15.3"
sdl2 = { version = "0.37.0", features = [] }
itertools = "0.13.0"
